<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CloudOrders.Domain\CloudOrders.Domain.csproj" />
    <ProjectReference Include="..\..\src\CloudOrders.Application\CloudOrders.Application.csproj" />
    <ProjectReference Include="..\..\src\CloudOrders.Infrastructure\CloudOrders.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\CloudOrders.Payment.Worker\CloudOrders.Payment.Worker.csproj" />
    <ProjectReference Include="..\..\src\CloudOrders.Inventory.Worker\CloudOrders.Inventory.Worker.csproj" />
    <ProjectReference Include="..\..\src\CloudOrders.Notification.Worker\CloudOrders.Notification.Worker.csproj" />
  </ItemGroup>

</Project>
