<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>CloudOrders.Notification.Worker</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudOrders.Application\CloudOrders.Application.csproj" />
    <ProjectReference Include="..\CloudOrders.Infrastructure\CloudOrders.Infrastructure.csproj" />
  </ItemGroup>

</Project>
